---
  TRADE_OPTIONS:
    QUANTITY: 50
    PAIRING: USDT
    # How often to check for posts in seconds
    RUN_EVERY: 600
    TEST: True
    SL: 1
    TP: 1
    ENABLE_TSL: True
    TSL: 0.5
    TTP: 2
